In [6]:
# Install plotly (only needed once)
!pip install plotly

Requirement already satisfied: plotly in C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from plotly) (26.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# ============================================
# STEP 1: Import Required Libraries
# ============================================

# pandas → used for handling data (like Excel but more powerful)
import pandas as pd

# numpy → used for numerical operations
import numpy as np

# matplotlib → basic plotting (used later for EDA)
import matplotlib.pyplot as plt

# seaborn → advanced plotting (used later for better visuals)
import seaborn as sns

# plotly → interactive visualizations (used for dashboard later)
import plotly.express as px

In [10]:
# ============================================
# STEP 3: Load IPC 2021 Dataset
# ============================================

# Load the Excel file into a pandas DataFrame
ipc_2021 = pd.read_excel("C:/Users/Varnika Sharma/Desktop/Crime Analysis/Crime Analysis/01_Data/Raw_Dataset/IPC_CRIMES/IPC_Crimes_Head-wise_Raw_2021.xlsx")

# Display first 5 rows to understand structure
ipc_2021.head()

,SL,State/UT,Offences affecting the Human Body,Offences affecting the Human Body.1,Offences affecting the Human Body.2,Offences affecting the Human Body.3,Offences affecting the Human Body.4,Offences affecting the Human Body.5,Offences affecting the Human Body.6,Offences affecting the Human Body.7,...,Miscellaneous IPC Crimes.50,Miscellaneous IPC Crimes.51,Miscellaneous IPC Crimes.52,Miscellaneous IPC Crimes.53,Miscellaneous IPC Crimes.54,Miscellaneous IPC Crimes.55,Miscellaneous IPC Crimes.56,Other IPC Crimes,Other IPC Crimes.1,Other IPC Crimes.2
0,NaN,NaN,Murder (Sec.302 IPC),Murder (Sec.302 IPC),Murder (Sec.302 IPC),Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Causing Death by Negligence,Causing Death by Negligence,...,Circulate False/Fake News/Rumours (Sec.505 IPC...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deaths due to Negligence relating to Road Acci...,Deaths due to Negligence relating to Road Acci...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A) Hit and Run,A) Hit and Run,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,I,V,R,I,V,R,I,V,...,R,I,V,R,I,V,R,I,V,R
4,1.0,Andhra Pradesh,956,985,1.8,112,134,0.2,739,761,...,0.1,2591,2631,4.9,2370,2384,9,27603,26679,52.2

In [13]:
# ============================================
# STEP 4: Load IPC 2021 Dataset (Clean Way)
# ============================================

# We skip the first few rows because they contain titles and merged headers
ipc_2021 = pd.read_excel(
    "C:/Users/Varnika Sharma/Desktop/Crime Analysis/Crime Analysis/01_Data/Raw_Dataset/IPC_CRIMES/IPC_Crimes_Head-wise_Raw_2021.xlsx")

# Preview the cleaned structure
ipc_2021.head()

,SL,State/UT,Offences affecting the Human Body,Offences affecting the Human Body.1,Offences affecting the Human Body.2,Offences affecting the Human Body.3,Offences affecting the Human Body.4,Offences affecting the Human Body.5,Offences affecting the Human Body.6,Offences affecting the Human Body.7,...,Miscellaneous IPC Crimes.50,Miscellaneous IPC Crimes.51,Miscellaneous IPC Crimes.52,Miscellaneous IPC Crimes.53,Miscellaneous IPC Crimes.54,Miscellaneous IPC Crimes.55,Miscellaneous IPC Crimes.56,Other IPC Crimes,Other IPC Crimes.1,Other IPC Crimes.2
0,NaN,NaN,Murder (Sec.302 IPC),Murder (Sec.302 IPC),Murder (Sec.302 IPC),Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Causing Death by Negligence,Causing Death by Negligence,...,Circulate False/Fake News/Rumours (Sec.505 IPC...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deaths due to Negligence relating to Road Acci...,Deaths due to Negligence relating to Road Acci...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A) Hit and Run,A) Hit and Run,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,I,V,R,I,V,R,I,V,...,R,I,V,R,I,V,R,I,V,R
4,1.0,Andhra Pradesh,956,985,1.8,112,134,0.2,739,761,...,0.1,2591,2631,4.9,2370,2384,9,27603,26679,52.2

In [15]:
# ============================================
# STEP 5 (FINAL): Assign Structured Column Names
# ============================================

# First 2 columns → SL and State
new_cols = ["SL", "State"]

# Remaining columns follow pattern I, V, R
remaining_cols = ipc_2021.shape[1] - 2

for i in range(remaining_cols):
    if i % 3 == 0:
        new_cols.append(f"Crime_{i//3+1}_I")
    elif i % 3 == 1:
        new_cols.append(f"Crime_{i//3+1}_V")
    else:
        new_cols.append(f"Crime_{i//3+1}_R")

# Assign new column names
ipc_2021.columns = new_cols

# Preview
ipc_2021.head()

,SL,State,Crime_1_I,Crime_1_V,Crime_1_R,Crime_2_I,Crime_2_V,Crime_2_R,Crime_3_I,Crime_3_V,...,Crime_116_V,Crime_116_R,Crime_117_I,Crime_117_V,Crime_117_R,Crime_118_I,Crime_118_V,Crime_118_R,Crime_119_I,Crime_119_V
0,NaN,NaN,Murder (Sec.302 IPC),Murder (Sec.302 IPC),Murder (Sec.302 IPC),Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Culpable Homicide not Amounting to Murder (Sec...,Causing Death by Negligence,Causing Death by Negligence,...,Circulate False/Fake News/Rumours (Sec.505 IPC...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Criminal Intimidation (Sec.506 r/w Other IPC C...,Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),Insult to the Modesty of Women (Sec.509 IPC),NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deaths due to Negligence relating to Road Acci...,Deaths due to Negligence relating to Road Acci...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A) Hit and Run,A) Hit and Run,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,I,V,R,I,V,R,I,V,...,R,I,V,R,I,V,R,I,V,R
4,1.0,Andhra Pradesh,956,985,1.8,112,134,0.2,739,761,...,0.1,2591,2631,4.9,2370,2384,9,27603,26679,52.2